export declare var loadData: () => Promise<typeof import("../data/s3.json")>;
export declare var ns: (term: string) => import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var _self: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var Bucket: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var FileStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var FrontendStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var QuadStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var bucket: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var endpoint: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var key: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare var secret: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
export declare const s3: {
    Bucket: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    FileStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    FrontendStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    QuadStore: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    bucket: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    endpoint: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    key: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
    secret: import("@_linked/core/utils/NodeReference.js").NodeReferenceValue;
};
